---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - image: nginx:latest
      name: test1
      volumeMounts:
        - mountPath: /cache
          name: cache-volume

    - image: bitnami/php-fpm:latest
      name: test2
      volumeMounts:
        - mountPath: /static
          name: cache-volume

  volumes:
    - name: cache-volume
      emptyDir: {} 
       
        
