---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    strategy: 10Gi
  accsessModes:
    - ReadWriteOnce
  hostPath:
    path: "mnt/data"
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cl
spec:
  accsessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    resources:
      storage: 10Gi
  storageClassName: manual    
    
---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pv
spec:
  containers:
    - image: nginx:latest
      name: test1
      volumeMounts:
        - mountPath: /cache
          name: test-pv-st

    - image: bitnami/php-fpm:latest
      name: test2
      volumeMounts:
        - mountPath: /static
          name: test-pv-st

  volumes:
    - name: test-pv-st
    PersistentVolumeClaim:
      claimName: test-cl 
