---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dinamic-volume-claim
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:    
      containers:
        - image: nginx:latest
          name: test1
          volumeMounts:
            - mountPath: /cache
              name: test-pv-st

        - image: bitnami/php-fpm:latest
          name: test2
          volumeMounts:
            - mountPath: /static
              name: test-pv-st

      volumes:
        - name: test-pv-st
          persistentVolumeClaim:
            claimName: test-dinamic-volume-claim
          

    